#!/usr/bin/env bash

# ATTENTION:
# Before calling this script, the Arduino needs to be erased. Until we figure
# out how to do that automatically, doing it manually is a feasible workaround.
# Just make sure to press the tiny "ERASE" button on the Arduino Due before
# uploading and everything should work.

clang \
	-nostdlib \
	-ffreestanding \
	-target arm-none-eabi \
	-march=armv7-m \
	-Tlinker-script.ld \
	-Wl,--entry=start \
	blink.c \
	-o blink.elf &&

arm-none-eabi-objcopy \
	-O binary \
	blink.elf \
	blink.bin &&

bossac --write --verify --boot -R blink.bin
