#!/usr/bin/env bash

# ATTENTION:
# Before calling this script, the Arduino needs to be erased. Until we figure
# out how to do that automatically, doing it manually is a feasible workaround.
# Just make sure to press the tiny "Erase" button on the Arduino Due before
# uploading and everything should work.

bossac --write --verify --boot -R $1
