#!/usr/bin/env bash

# ATTENTION:
# Before calling this script, the Arduino needs to be erased. Until we figure
# out how to do that automatically, doing it manually is a feasible workaround.
# Just make sure to press the tiny "ERASE" button on the Arduino Due before
# uploading and everything should work.

./compile &&

arm-none-eabi-objcopy \
	-O binary \
	output/blink.elf \
	output/blink.bin &&

(
    cd uploader
    cargo run -- /dev/ttyACM0 upload-file ../output/blink.bin)
